### ISSUE TITLE
Error: Library cublas64_12.dll is not found or cannot be loaded

### ISSUE THREAD

**Issue by videoprice** [jhj0517/Whisper-WebUI#102]
hi guys, have this error when start generate subtitle file
"Error: Library cublas64_12.dll is not found or cannot be loaded"

win 11 rtx 3090

**Comment by CUBER980** [comment]
Mismo error
Error transcribing file on line Library cublas64_12.dll is not found or cannot be loaded
win 11 rtx 4060 TI

**Comment by jhj0517** [comment]
Hi. Like #97, this is fixed in #99.
This problem is caused by an incompatible version of faster-whisper with CUDA versions below 12.0, 
1. trying latest version of the web-ui ( removing venv folder and run install.bat again )

2.  Or just
```
# After activating the venv
pip uninstall faster-whisper
pip install faster-whisper==0.10.1
``` 
Using the version of faster-whisper==0.10.1 solves this problem.

**Comment by videoprice** [comment]
Thanks, working

**Comment by CUBER980** [comment]
Correcto, solucionado, gracias.
