### ISSUE TITLE
Batch Download of transcript files

### ISSUE THREAD

**Issue by boederzeng** [jhj0517/Whisper-WebUI#156]
Im currently batch transcriping tons of mp4s. while batch adding is working fine in the dropdown field you currently can not batch download all created srt files. respectfully asking for this to be added. furthermore short question, are there better models than v3 out there? would it make sense to add them? 

THANKS

**Comment by jhj0517** [comment]
Hi! 
>> can not batch download all created srt files

Currently, all output subtitles are saved in the [./outputs](https://github.com/jhj0517/Whisper-WebUI/tree/master/outputs)  folder. You can download them from there. 
Is there any inconvenience with this?

>> better models than v3 out there

The `large-v3` is now the latest model in Whisper. So the `large-v3` should be the best one if you can use it with your GPU.
But according to this [comment](https://github.com/jhj0517/Whisper-WebUI/issues/152#issuecomment-2123817314), sometimes you get better results with `large-v2` instead of `large-v3`. So I recommend switching between them for your needs.

**Comment by boederzeng** [comment]
> Currently, all output subtitles are saved in the [./outputs](https://github.com/jhj0517/Whisper-WebUI/tree/master/outputs) folder. You can download them from there.
Is there any inconvenience with this?

Sorry, silly mistake on my end. You are right, no, thats perfect. Sorry for bothering. Also thanks for comment regarding models. Keep up the great work.
