### ISSUE TITLE
when i use vad, the timestamp doesn't works

### ISSUE THREAD

**Issue by kdg1257** [jhj0517/Whisper-WebUI#212]
**Which OS are you using?**
 - OS: colab
 
when I use vad filter, it cutoffs all of the blanks with no voice, so the timestamp doesn't matches with original video

**Comment by jhj0517** [comment]
Hi @kdg1257. Thanks for raising the issue.

The current behavior follows the default VAD implementation within faster-whisper and it cuts off the non-speech part.

And this is definitely not the desired action when generating the subtitle. 
Need to add a parameter like `silence_non_speech` instead of just cutting off.

**Comment by jhj0517** [comment]
@kdg1257 with #213, it should work now. 
Let me know if it persists

**Comment by jhj0517** [comment]
I have confirmed that bug exists. Looking into it now.

**Comment by jhj0517** [comment]
I confirmed

**Comment by jhj0517** [comment]
The VAD module was incorrectly implemented. Investigating a proper implementation.

**Comment by jhj0517** [comment]
With #214, the VAD should work fine now.

VAD is now only usable in faster-whisper.
I made a new issue about it in #215.

Please feel free to re-open if you still face any errors!
