### ISSUE TITLE
Add ability to disable filename sanitation

### ISSUE THREAD

**Issue by 9SMTM6** [jhj0517/Whisper-WebUI#232]
In #193 I noted that you do a few things to the filename [here](https://github.com/jhj0517/Whisper-WebUI/blob/60697fb8ab88ef04fe308f6f746773b091149e77/modules/utils/subtitle_manager.py#L121).

I've since experimentally disabled any sanitation in a local dockerfile, by just returning the input in that method. And it worked well for my purpose. Not only diesnt it cut off the filename, all the naming remains (e.g. `:` in a filename).

I'm uncertain why you did this, but if we would be given an option to disable this then I'd appreciate it!

**Comment by jhj0517** [comment]
Hi @9SMTM6. Some OS (e.g. Windows) do not allow characters like `:` and too long filename.
If there's no `safe_filename()`, it sometimes causes an error when transcribing via Youtube API because of the title.

Of course, this most likely happens when you're only transcribing from Youtube.
I think it's probably safe to disable this when transcribing a local file, because it probably already has a safe filename.

**Comment by 9SMTM6** [comment]
@jhj0517 thanks for the info. 

Blanko disabling it does seem to cause some issues with certain filename. It probably executes unintended codepaths. I believe the trigger was multiple dots in the filename. I'll have to come back to you for that, just wanted to let you know.

**Comment by jhj0517** [comment]
Thanks for bringing this up.
Since `gradio` already does the filename sanitization, I don't think I need to do it twice.

`safe_filename()` is disabled when transcribing a local file in #234. 
Please feel free to reopen the issue if you encounter any problems!
