### ISSUE TITLE
Software is not compatible with clash for windows

### ISSUE THREAD

**Issue by zuiaiyutu** [jhj0517/Whisper-WebUI#241]
In windows 11, when clash for windows is running in the background and the software is launched, an error will be reported. When you turn off clash for windows, it will work normally.
![报错](https://github.com/user-attachments/assets/d17ce9ba-758c-4229-a85c-4539ddf2ba15)

**Comment by jhj0517** [comment]
The related issue is 
- https://github.com/chenfei-wu/TaskMatrix/issues/250

It seems that this is not Windows specific, this happens when you set proxy on your machine. ( Or you may have VPN turned on ?? )

As recommended by this [comment](https://github.com/chenfei-wu/TaskMatrix/issues/250#issuecomment-1498285842), 
You can edit the [start-webui.bat](https://github.com/jhj0517/Whisper-WebUI/blob/master/start-webui.bat) to add the `set no_proxy=localhost` like this:

```
@echo off

call venv\scripts\activate

:: Add this line
set no_proxy=localhost, 127.0.0.1, ::1 

python app.py %CLI_ARGS%

echo "launching the app"
pause
```

**Comment by zuiaiyutu** [comment]
yes,clash for windows is a vpn software.
After I modified the start-webui.bat with the following code, the software works normally, thank you.

@echo off

call venv\scripts\activate

:: Add this line
set no_proxy=localhost, 127.0.0.1, ::1 

python app.py %CLI_ARGS%

echo "launching the app"
pause
