### ISSUE TITLE
Can't install properly, installation error

### ISSUE THREAD

**Issue by zuiaiyutu** [jhj0517/Whisper-WebUI#274]
win 11 23H2 22631.4169  
cuda12.6.65 
python 3.12.5
Can't install properly, installation error
![QQ截图20240915123507](https://github.com/user-attachments/assets/5233e6db-b40c-4bc8-8996-b62d9c3252da)

**Comment by jhj0517** [comment]
OK, there seems to be a version incompatibility issue with `python >= 3.12` : [stackoverflow post](https://stackoverflow.com/questions/77274572/multiqc-modulenotfounderror-no-module-named-imp)

I tried to handle it in the forked pyrubberband so that it's also compatible in `python >= 3.12`. 

Can you try again?

**Comment by zuiaiyutu** [comment]
Thank you. I tried it again and it works fine
