### ISSUE TITLE
Translated srt timestamps are rounded to the nearest second

### ISSUE THREAD

**Issue by JeremyMahieu** [jhj0517/Whisper-WebUI#28]
An output SRT file that has been translated all has timings exactly on the second and 000ms. While in the original language does not exactly fall on the second each time.

This with checking the "translate to english" checkbox. Not when using the T2T translation

**Which OS are you using?**
 - OS: Windows 11

**Comment by jhj0517** [comment]
Hi @JeremyMahieu. Thanks for pointing this out.
This only happens when using the "Translate to English?" option, right?
This option is a feature of the Whipser model that translates speech directly into English text End-to-End.
It is not something I implemented myself, but a feature of the Whisper model. 

It seems that it may deliver less accurate timestamps when in use. That's a good piece of information to have.

Honestly, there's nothing I can do about it, so I'll close this issue soon!

**Comment by JeremyMahieu** [comment]
Yeah only with that checkbox. Alright thanks.
