### ISSUE TITLE
Error in the middle of transcribing

### ISSUE THREAD

**Issue by DAWiguna** [jhj0517/Whisper-WebUI#281]
**I use Windows 11, RTX 3080 10GB VRAM, 32GB RAM, and implement Whisper using Pinokio**
At first there are problem with cudnn, but after get them from cuda zip, simply unzip cudnn_ to CUDA\bin in Program Files. Then, it could run if short

Then I put our video to be subtitled. It ran for about 1 minute, then Error. But in Terminal (pinokio) there were no error messages. Whisper simply just stop in the middle.

I use model Large-v3, set Beam to 5. Any other setting that I should know about?

**Comment by jhj0517** [comment]
As far as I know, Pinokio uses an older version of this WebUI and it may be problematic because of using an older version of CUDA etc.

I raised the [issue](https://github.com/cocktailpeanut/whisper-webui.pinokio/issues/5) to update the WebUI to the repository that pinokio may be using.

I recommend using [Whisper-WebUI-Portable-Windows.zip](https://github.com/jhj0517/Whisper-WebUI/releases/tag/v1.0.0) for now.

**Comment by DAWiguna** [comment]
Thanks, I guess that's the best.
