### ISSUE TITLE
Is it possible to use Gradio Theme Gallery?

### ISSUE THREAD

**Issue by neuralnermal** [jhj0517/Whisper-WebUI#33]
Hello, I like this WebUI for its simplicity, but was wondering if I could customize some visual elements.
Is it possible to Gradio Theme Gallery? : https://huggingface.co/spaces/gradio/theme-gallery

I'm assuming this WebUI is built with Gradio, but correct me if I'm wrong

Also wondering if there are any localization options

**Comment by jhj0517** [comment]
Hi, @neuralnermal. 
This project is built with Gradio, so you can apply themes by editing the code 

`self.app = gr.Blocks(css=CSS, theme='example_theme')` in `app.py`.

You can also apply your own CSS by editing the `CSS` value in `ui\htmls.py`. You can inspect each element's id with F12 (browser inspect tool).

Regarding the localization, you mean the label text of each component, right?
According to [#gradio 2465](https://github.com/gradio-app/gradio/issues/2465), it seems Gradio does not officially support the localization option yet. However, you can achieve it with a bit of workaround code, as mentioned [here](https://github.com/gradio-app/gradio/issues/2465#issuecomment-1447608018).

It would be great to use the localization if Gradio officially supports it. But since it is not an official option yet, I will look into this workaround code or consider making a pull request to Gradio later.

**Comment by jhj0517** [comment]
added new command line argument in [#0f16dda](https://github.com/jhj0517/Whisper-WebUI/commit/0f16dda2d71e3a9ba6afc906eb0a53ff36935aad).

You can use 

`python app.py --theme author/example_theme`

or set the THEME value in the user-start-webui.bat file and run the batch file.

**Comment by jhj0517** [comment]
resolve, closing it
