### ISSUE TITLE
Non-Windows install instructions?

### ISSUE THREAD

**Issue by drscotthawley** [jhj0517/Whisper-WebUI#89]
**Describe the feature you'd like**

I was looking forward to trying this until I got to the part in the README that says:

> Run Install.bat from Windows Explorer as a regular, non-administrator user.

Request: Would love to see installation instructions for non-Windows users. 

Reason:  I'm on a Mac. I also have access to a Linux machine.  No Windows.

**Comment by jhj0517** [comment]
Hi @drscotthawley, Thanks for raising the issue.
In case if you are using Mac, you can use shell script like `install.sh`.
You can run `install.sh` and then run `start-webui.sh` to run the WebUI after installation.
I should have added this to the ReadME, so I've added it now.

But I'm not sure if the shell script would work because I haven't tested it on the Mac.

If encounter any problem during the process, please let me know.

**Comment by kwongiho** [comment]
Hello. I'm currently using a Mac. Looking at the Git commit history, it seems that the shell script was deleted yesterday. Do you have any plans to restore it in the future?

**Comment by jhj0517** [comment]
Hi @kwongiho, the project has a Dockerfile but if you're unable to use Docker,
It would definitely be better to have shell script. 
I removed the shell script because just it contained errors, and I don't have the environment to test them.

Any PR about it would be very appreciated. 

For now, please install and run it manually by :

For installation : 
```python
python -m venv venv 
source venv/bin/activate
pip install -r requirements.txt
```

To run :
```python
source venv/bin/activate
python app.py
```

**Comment by jhj0517** [comment]
Shell scripts are now added in #125, so this is closed.
Please feel free to reopen if you find any errors!

**Comment by Fanlen** [comment]
> 你好@drscotthawley，感谢您提出这个问题。 如果您使用的是 Mac，则可以使用类似 的 shell 脚本`install.sh`。 您可以在安装后运行`install.sh`然后运行`start-webui.sh`以运行 WebUI。 我应该将其添加到 ReadME 中，所以我现在添加了它。
> 
> 但我不确定该 shell 脚本是否可行，因为我还没有在 Mac 上测试过。
> 
> 如果您在此过程中遇到任何问题，请告诉我。

@jhj0517 可以使用，最好加入到安装说明下，还有很多macbook是python3 / 
pip3 所以可以在安装说明下确定当前的macos环境python的相关环境
